### ISSUE TITLE
Incompatibility unknown to package manager: typing_extensions=4.5.0, notebooks, python=3.10

### ISSUE THREAD

**Issue by Alexandre-aksenov** [python/typing_extensions#441] opened 2024-07-29 09:19 UTC
I discovered, by the path of trial-and-error, that the version typing_extensions=4.5.0 is incompatible with notebooks in versions of python starting from 3.10. I suggest that this incompatibility be communicated to package managers to avoid installing broken environments to the future users.

**Steps to reproduce the issue.**

Create an environment using:`
conda create -n test_typing_py10 --channel=conda-forge python=3.10 typing_extensions=4.5.0`

Create a minimal notebook `test_typing.ipynb` with one cell:
`print(1 +2)`

Try running it in the newly-created environment, observe the error message:
`The kernel failed to start as 'TypeAliasType' could not be imported from typing_extensions.py`

On the other hand, the modules (.py) work smoothly.

**What makes this issue problematic**
My personal project is about image classification, it does not (currently) use the features of `typing_extensions` . The library appears as it is required by `tensorflow=2.13`. On the other hand, it is problematic to switch to a lower version of python as `python=10` is currently required by the library `streamlit`. I hope, if this incompatibility is communicated to package managers (pip, conda), this wouldl simplify the work to future users.  Thanks in advance!

**Comment by AlexWaygood** [comment] 2024-07-29 09:23
What version of `ipython` is installed into your environment? This looks like https://github.com/ipython/ipython/issues/14380

**Comment by AlexWaygood** [comment] 2024-07-29 10:21
Okay, great! That confirms that the issue is https://github.com/ipython/ipython/issues/14380. This was a bug in IPython where they were relying on features added in `typing_extensions==4.6.0`, but didn't declare that in their packaging metadata. The bug was fixed in `ipython==8.24.0`. You should hopefully find that your issue is fixed if you do one of the following to your Conda environment:
- Upgrade the version of `ipython` to `8.24.0` and the version of `typing_extensions` to `4.6.0`, or
- Downgrade the version of `ipython` to `8.22.0`

I'm afraid there's not really anything else we can do here, since this wasn't a bug in `typing_extensions`. Possibly you could request `ipython` to yank the `8.23.0`, since the packaging bug they have in that version appears to be causing package managers such as Conda to install an incompatible version of `ipython` into an environment if you request `typing_extensions==4.5.0`. That would be a decision for `ipython` to make, however.

**Closed by AlexWaygood** 2024-07-29 10:21 UTC

**Comment by Alexandre-aksenov** [comment] 2024-07-29 14:46
Many thanks! The first option You suggested allowed my existing programs to work!

Sorry for bothering You with an issue, which had already been  reported. My fault that I did not manage to identify the  [previous issue](https://github.com/ipython/ipython/issues/14380) as being the same.

**Comment by AlexWaygood** [comment] 2024-07-29 14:48
No worries @Alexandre-aksenov, it happens :-) glad your issue is fixed!
