### ISSUE TITLE
TypeError after upgrading version to 4.6.0

### ISSUE THREAD

**Issue by vkukushkin88** [python/typing_extensions#182] opened 2023-05-23 15:38 UTC
/usr/local/lib/python3.9/typing.py:852: in __subclasscheck__
    return issubclass(cls, self.__origin__)
E   TypeError: issubclass() arg 1 must be a class

Object declaration: 

class RelocationUnit(BaseFrozenModel):
    """Relocation object."""

    type: Literal[RelocationType.locale,
                  RelocationType.teleport,
                  RelocationType.car,
                  RelocationType.forced]
    relocation_time: timedelta
    airport_from: Airport
    airport_to: Airport
    start_time: datetime
    end_time: datetime

on 4.5.0 or less it works perfectly.

**Comment by AlexWaygood** [comment] 2023-05-23 15:41
Duplicate of https://github.com/pydantic/pydantic/issues/5821, I believe. There's already been a pydantic PR merged that fixes the issue, we're just waiting for a pydantic release that includes the fix

**Closed as not planned by AlexWaygood** 2023-05-23 15:41 UTC
