### ISSUE TITLE
`Required`/`NotRequired` don't work with `__future__.annotations`

### ISSUE THREAD

**Issue by jcrist** [python/typing_extensions#55] opened 2022-07-11 17:49 UTC
`Required`/`NotRequired` aren't properly detected when `from __future__ import annotations` is used, leading to incorrect `__required_keys__`/`__optional_keys__` sets.

Reproduced with 4.3.0.

```python
from __future__ import annotations  # comment this line out and things work correctly
from typing_extensions import NotRequired, TypedDict

class Test(TypedDict):
    a: int
    b: NotRequired[int]

assert Test.__required_keys__ == {"a"}
assert Test.__optional_keys__ == {"b"}
```

```shell
$ python test.py
Traceback (most recent call last):
  File "/home/jcristharif/Code/test.py", line 8, in <module>
    assert Test.__required_keys__ == {"a"}
AssertionError
```

**Comment by JelleZijlstra** [comment] 2022-07-11 18:06
What Python version are you running? Does this reproduce with `typing` too on Python 3.11?

**Comment by jcrist** [comment] 2022-07-11 18:11
I don't have (easy) access to a 3.11 build, but it reproduces with 4.3.0 on both 3.10 and 3.9.

**Comment by AlexWaygood** [comment] 2022-07-12 13:10
I can reproduce using `typing.TypedDict` and `typing.NotRequired` on CPython `main` branch (3.12), so I assume it reproduces on 3.11 as well.

**Comment by yixun-alpha** [comment] 2022-09-02 08:15
just ran into this issue with 4.3.0 and python 3.7.6 - any fix in the works? thanks!

**Comment by gvanrossum** [comment] 2022-09-02 16:42
So is this fixed by #60 or not? It seems to be an issue with the upstream cpython typing module as well -- did someone already file an issue there? Please link it here.

**Comment by JelleZijlstra** [comment] 2022-09-02 17:45
#60 would fix this in simple cases, but I think it will cause more problems than it solves. I'm inclined to wontfix this. Maybe we can revisit once there's a resolution on the PEP 563/649 saga.

**Comment by gvanrossum** [comment] 2022-09-02 18:33
It's fine to not want to solve this for now. In fact one could argue that, since the point of `from __future__ import annotations` is not to incur runtime costs, you get what you ask for. (Not sure if that's totally fair, but it's a possible POV.)

**Comment by srittau** [comment] 2024-09-02 19:53
I'm closing this here in favor of python/cpython#97727. It seems that the consensus is that it's too complex to fix and will go away by itself at some distant point in the future when the future import isn't required anymore.

**Closed by srittau** 2024-09-02 19:53 UTC

**Comment by Daraan** [comment] 2025-03-28 20:08
I now had this problem too. Inspired by https://github.com/python/cpython/issues/97727#issuecomment-1267799861 I made these 4 utility functions to get the correct `__required_keys__` / `__optional_keys__`, extend for `__readonly_keys__` in a similar way.

```python
from typing_extensions import NotRequired, Required, get_origin, get_type_hints

fixed_args = mock.patch.object(sys, "argv", ["file.py", "--no-render_env"])
clean_args = mock.patch.object(sys, "argv", ["file.py"])
"""Use when comparing to CLIArgs"""

def get_explicit_required_keys(cls):
    return {k for k, v in get_type_hints(cls, include_extras=True).items() if get_origin(v) is Required}

def get_explicit_unrequired_keys(cls):
    return {k for k, v in get_type_hints(cls, include_extras=True).items() if get_origin(v) is NotRequired}

def get_required_keys(cls):
    return cls.__required_keys__ - get_explicit_unrequired_keys(cls)

def get_optional_keys(cls):
    return cls.__optional__keys - get_explicit_required_keys(cls)
```
